<?php /*
 Template Name: Biotope
 */

 ?>



<!doctype html>
<html class="no-js" lang="en">


<head>
	<meta charset="utf-8">

<!-- Use the .htaccess and remove these lines to avoid edge case issues. More info: h5bp.com/b/378 -->
<!-- DEV NOTE: whenever possible set the HTTP-Header for X-UA-Compatible too to avoid problems with intranet zones -->
<meta http-equiv="x-ua-compatible" content="ie=edge">

<title>SnapLayout</title>
<meta name="description" content="include meta description here">

<!-- Mobile viewport optimized: h5bp.com/viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="msapplication-tap-highlight" content="no">
<!-- do not detect phone numbers -->
<meta name="format-detection" content="telephone=no">

<meta property="og:title" content="use same as page title">
<meta property="og:description" content="use same as meta description">
<meta property="og:type" content="website">

<!--DEV-NOTE: next two exntries are optional. define a custom share image and URL or remove this two lines -->
<meta property="og:url" content="">
<meta property="og:image" content="">


	<!-- inject:head:html -->
	<link rel="apple-touch-icon" sizes="57x57" href="favicons/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="favicons/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="favicons/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="favicons/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="favicons/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="favicons/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="favicons/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="favicons/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="favicons/apple-touch-icon-180x180.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="gulp-frontend-boilerplate">
<link rel="icon" type="image/png" sizes="228x228" href="favicons/coast-228x228.png">
<link rel="yandex-tableau-widget" href="favicons/yandex-browser-manifest.json">
<link rel="manifest" href="favicons/manifest.json">
<meta name="mobile-web-app-capable" content="yes">
<meta name="theme-color" content="#020307">
<meta name="application-name" content="gulp-frontend-boilerplate">
<link rel="icon" type="image/png" sizes="32x32" href="favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="favicons/favicon-16x16.png">
<link rel="shortcut icon" href="favicons/favicon.ico">
<meta name="msapplication-TileColor" content="#020307">
<meta name="msapplication-TileImage" content="favicons/mstile-144x144.png">
<meta name="msapplication-config" content="favicons/browserconfig.xml">
	<!-- endinject -->

	<!-- DEV-note: include page specific meta information after this comment -->

	<!-- CSS: implied media=all -->
<!-- CSS should be concatenated and minified in production use -->

<!-- The following files are merged into resources/css/styles.all.min.css -->
<link rel="stylesheet" href="resources/css/styles.all.min.css">

<!-- The following files are merged into resources/css/styles.print.min.css -->
<link rel="stylesheet" href="resources/css/styles.print.min.css" media="print">


	<!-- All JavaScript at the bottom, except for Modernizr and configuration class -->

<script src="resources/js/scripts.head.all.min.js"></script>

<!-- Site-specific configurations like CDN resource folder or current page ID -->
<script type="text/javascript">
	biotope.configuration.set('data.staticResourcesBase', 'resources/');
	biotope.configuration.set('data.staticResourcesContentRepoBase', 'resources-content/');
</script>

	<!-- DEV-note: include page specific styles and scripts after this comment -->
</head>

<body role="document" class="">
	<main class="content">
		<article>
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyARr8Ibkxk8wCZ36Jcv8UxfS64FyTGJRmg"></script>
<snap-layout data-resources="[{paths: ['components/SnapLayout/index.js']}]"></snap-layout>

		</article>
	</main>
	<!--  global variables and language specific js generated by the CMS -->
<script src="_config/configuration.js"></script>

<!-- concatenate and minify script for live environment -->
<script src="resources/js/scripts.all.min.js"></script>



	<!-- DEV-note: include page specific scrips after this comment -->
</body>

</html>
