
<?php /*
 Template Name: Biotope
 */

 ?>

  

<!doctype html>
<html class="no-js" lang="en">


<head>
<?php include_once('./htmlhead.php'); ?>
</head>

<body role="document" class="">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TVJN724"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
	<main class="content">
		<article>
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyARr8Ibkxk8wCZ36Jcv8UxfS64FyTGJRmg"></script>
<script src="/konferenz/resources/components/Conference/index.js"></script>
<x-conference></x-conference>

		</article>
	</main>
	<!--  global variables and language specific js generated by the CMS -->
<script src="/konferenz/_config/configuration.js"></script>

<script src="https://www.google.com/recaptcha/api.js?render=6LfZ66EUAAAAAGouKeuOgH_6_Ph92AJoQyBb-MIU"></script>
<!-- concatenate and minify script for live environment -->
<script src="/konferenz/resources/js/scripts.all.min.js"></script>

	

	<!-- DEV-note: include page specific scrips after this comment -->
</body>

</html>